const state = { tempo: 96, isPlaying: false, currentBeat: 0, tool: 'select', grid: 1 / 16, zoom: 100, playTimer: 0, notes: [
  { pitch: 72, start: 0, length: 1, label: 'C5' }, { pitch: 76, start: 1, length: 1, label: 'E5' }, { pitch: 79, start: 2, length: 1, label: 'G5' }, { pitch: 76, start: 3, length: 1, label: 'E5' },
  { pitch: 74, start: 4, length: 1, label: 'D5' }, { pitch: 77, start: 5, length: 1, label: 'F5' }, { pitch: 81, start: 6, length: 2, label: 'A5' }, { pitch: 77, start: 8, length: 1, label: 'F5' },
  { pitch: 72, start: 9, length: 1, label: 'C5' }, { pitch: 76, start: 10, length: 1, label: 'E5' }, { pitch: 79, start: 11, length: 1, label: 'G5' }, { pitch: 84, start: 12, length: 3, label: 'C6' }
] };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const pitchNames = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
const isBlack = (pitch) => [1, 3, 6, 8, 10].includes(pitch % 12);
const pitchLabel = (pitch) => `${pitchNames[pitch % 12]}${Math.floor(pitch / 12) - 1}`;

function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timeout); showToast.timeout = setTimeout(() => toast.classList.remove('visible'), 2200); }
function renderKeyboard() { const keyboard = $('#keyboard'); keyboard.innerHTML = ''; for (let pitch = 84; pitch >= 53; pitch -= 1) { const key = document.createElement('div'); key.className = `key-label ${isBlack(pitch) ? 'black' : ''}`; key.textContent = pitchLabel(pitch); keyboard.appendChild(key); } }
function renderTimeline() { const timeline = $('#timeline'); timeline.innerHTML = ''; for (let bar = 1; bar <= 4; bar += 1) { const label = document.createElement('span'); label.className = 'bar-label'; label.style.left = `${(bar - 1) * 240 + 8}px`; label.textContent = String(bar).padStart(2, '0'); timeline.appendChild(label); } }
function renderNotes() {
  const roll = $('#pianoRoll'); roll.querySelectorAll('.note').forEach((note) => note.remove()); const pixelsPerBeat = 60 * state.zoom / 100;
  state.notes.forEach((note, index) => { const element = document.createElement('div'); element.className = `note ${isBlack(note.pitch) ? 'black-key' : ''}`; element.dataset.index = index; element.textContent = note.label || pitchLabel(note.pitch); element.style.left = `${note.start * pixelsPerBeat + 2}px`; element.style.top = `${(84 - note.pitch) * 30 + 4}px`; element.style.width = `${Math.max(note.length * pixelsPerBeat - 4, 14)}px`;
    element.addEventListener('click', (event) => { event.stopPropagation(); if (state.tool === 'erase') { state.notes.splice(index, 1); renderNotes(); } else { $$('.note').forEach((item) => item.classList.remove('selected')); element.classList.add('selected'); } }); roll.appendChild(element); });
  $('#noteSummary').textContent = `${state.notes.length} notes · 1 bar`;
}
function renderAll() { renderKeyboard(); renderTimeline(); renderNotes(); }
function setPlaying(playing) { state.isPlaying = playing; $('#playButton').classList.toggle('playing', playing); $('#playIcon').innerHTML = playing ? '&#10074;&#10074;' : '&#9654;'; }
function updateTime() { const seconds = state.currentBeat * 60 / state.tempo; const mins = Math.floor(seconds / 60).toString().padStart(2, '0'); const secs = Math.floor(seconds % 60).toString().padStart(2, '0'); $('#currentTime').textContent = `00:${mins}:${secs}`; $('#beatCounter').textContent = `${Math.floor(state.currentBeat / 4) + 1}.${Math.floor(state.currentBeat % 4) + 1}`; $('#playhead').style.left = `${state.currentBeat * 60 * state.zoom / 100}px`; }
function startPlayback() { if (state.isPlaying) return; setPlaying(true); const tick = () => { if (!state.isPlaying) return; state.currentBeat += .05; if (state.currentBeat >= 16) state.currentBeat = 0; updateTime(); state.playTimer = requestAnimationFrame(tick); }; state.playTimer = requestAnimationFrame(tick); }
function stopPlayback() { setPlaying(false); cancelAnimationFrame(state.playTimer); }
function addNoteAt(event) { if (state.tool === 'select' || state.tool === 'erase') return; const roll = $('#pianoRoll').getBoundingClientRect(); const pixelsPerBeat = 60 * state.zoom / 100; const pitch = Math.max(53, Math.min(84, 84 - Math.floor((event.clientY - roll.top) / 30))); const start = Math.max(0, Math.round((event.clientX - roll.left) / pixelsPerBeat / state.grid) * state.grid); if (state.notes.some((note) => note.pitch === pitch && Math.abs(note.start - start) < .01)) return; state.notes.push({ pitch, start, length: state.grid * 4, label: pitchLabel(pitch) }); renderNotes(); }
function variableBytes(value) { const bytes = [value & 127]; while ((value >>= 7)) bytes.unshift((value & 127) | 128); return bytes; }
function exportMidi() { const ticks = 480; const events = []; state.notes.forEach((note) => { events.push({ tick: Math.round(note.start * ticks), data: [0x90, note.pitch, 96] }); events.push({ tick: Math.round((note.start + note.length) * ticks), data: [0x80, note.pitch, 0] }); }); events.sort((a, b) => a.tick - b.tick); let previous = 0; const track = []; events.forEach((event) => { track.push(...variableBytes(event.tick - previous), ...event.data); previous = event.tick; }); track.push(0, 0xff, 0x2f, 0); const header = [77, 84, 104, 100, 0, 0, 0, 6, 0, 0, 0, 1, 1, 224]; const size = track.length; const bytes = [...header, 77, 84, 114, 107, (size >>> 24) & 255, (size >>> 16) & 255, (size >>> 8) & 255, size & 255, ...track]; const blob = new Blob([new Uint8Array(bytes)], { type: 'audio/midi' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${$('#projectTitle').textContent.replace(/\s+/g, '-') || 'untitled-session'}.mid`; link.click(); URL.revokeObjectURL(link.href); showToast('MIDI exported from Soft Keys'); }
function readVariable(bytes, cursor) { let value = 0; let byte; do { byte = bytes[cursor.index++]; value = (value << 7) | (byte & 127); } while (byte & 128); return value; }
function importMidi(file) { const reader = new FileReader(); reader.onload = () => { const bytes = new Uint8Array(reader.result); let offset = 0; while (offset < bytes.length - 3 && String.fromCharCode(...bytes.slice(offset, offset + 4)) !== 'MTrk') offset += 1; if (offset >= bytes.length - 3) return showToast('Could not find a MIDI track'); const length = (bytes[offset + 4] << 24) | (bytes[offset + 5] << 16) | (bytes[offset + 6] << 8) | bytes[offset + 7]; const track = bytes.slice(offset + 8, offset + 8 + length); const cursor = { index: 0 }; let tick = 0; let running = 0; const active = {}; const imported = []; while (cursor.index < track.length) { tick += readVariable(track, cursor); let status = track[cursor.index++]; if (status < 128) { cursor.index -= 1; status = running; } else running = status; if (status === 0xff) { cursor.index += 1; const metaLength = readVariable(track, cursor); cursor.index += metaLength; continue; } if ((status & 0xf0) === 0x90 || (status & 0xf0) === 0x80) { const pitch = track[cursor.index++]; const velocity = track[cursor.index++]; const key = `${pitch}`; if ((status & 0xf0) === 0x90 && velocity) active[key] = { pitch, tick }; else if (active[key]) { const start = active[key]; imported.push({ pitch, start: start.tick / 480, length: Math.max((tick - start.tick) / 480, .25), label: pitchLabel(pitch) }); delete active[key]; } } else if ((status & 0xf0) === 0xc0 || (status & 0xf0) === 0xd0) cursor.index += 1; else cursor.index += 2; } if (imported.length) { state.notes = imported.slice(0, 120); renderNotes(); showToast(`${state.notes.length} MIDI notes imported`); } else showToast('No playable notes found in MIDI'); }; reader.readAsArrayBuffer(file); }

renderAll(); updateTime();
$('#playButton').addEventListener('click', () => state.isPlaying ? stopPlayback() : startPlayback()); $('#stopButton').addEventListener('click', () => { stopPlayback(); state.currentBeat = 0; updateTime(); }); $('#rewind').addEventListener('click', () => { state.currentBeat = 0; updateTime(); });
$('#tempoDown').addEventListener('click', () => { state.tempo = Math.max(40, state.tempo - 1); $('#tempoValue').textContent = state.tempo; }); $('#tempoUp').addEventListener('click', () => { state.tempo = Math.min(220, state.tempo + 1); $('#tempoValue').textContent = state.tempo; });
$$('.mode-tab').forEach((tab) => tab.addEventListener('click', () => { $$('.mode-tab').forEach((item) => item.classList.remove('active')); tab.classList.add('active'); showToast(tab.dataset.view === 'music-page' ? 'Music Page view: all notes visible' : 'Arrangement view selected'); }));
$$('.tool-button').forEach((button) => button.addEventListener('click', () => { state.tool = button.dataset.tool; $$('.tool-button').forEach((item) => item.classList.toggle('active', item === button)); })); $$('.small-control').forEach((button) => button.addEventListener('click', () => { state.grid = button.dataset.grid === '1/4' ? .25 : button.dataset.grid === '1/8' ? .125 : .0625; $$('.small-control').forEach((item) => item.classList.toggle('active', item === button)); }));
$('#pianoRoll').addEventListener('dblclick', addNoteAt); $('#zoomSlider').addEventListener('input', (event) => { state.zoom = Number(event.target.value); $('#zoomValue').textContent = `${state.zoom}%`; renderNotes(); }); $('#importMidiButton').addEventListener('click', () => $('#midiInput').click()); $('#midiInput').addEventListener('change', (event) => event.target.files[0] && importMidi(event.target.files[0])); $('#exportMidiButton').addEventListener('click', exportMidi); $('#exportMidiTop').addEventListener('click', exportMidi);
$$('[data-action]').forEach((button) => button.addEventListener('click', (event) => { event.stopPropagation(); button.classList.toggle('active'); })); $$('.track-card').forEach((card) => card.addEventListener('click', () => { $$('.track-card').forEach((item) => item.classList.remove('selected')); card.classList.add('selected'); }));
function addTrack() { const track = document.createElement('div'); track.className = 'track-card'; track.innerHTML = '<div class="track-color cyan"></div><div class="track-card-main"><div class="track-name">New MIDI Track <span class="track-type">MIDI</span></div><div class="track-meta">Grand piano · 04</div></div><button class="track-menu">···</button><div class="track-buttons"><button class="track-toggle" data-action="mute">M</button><button class="track-toggle" data-action="solo">S</button><button class="track-arm" data-action="arm">REC</button></div>'; $('#trackList').appendChild(track); track.addEventListener('click', () => { $$('.track-card').forEach((item) => item.classList.remove('selected')); track.classList.add('selected'); }); showToast('MIDI track added'); }
$('#addTrack').addEventListener('click', addTrack); $('#addTrackBottom').addEventListener('click', addTrack); $('#newProject').addEventListener('click', () => { state.notes = []; renderNotes(); $('#projectTitle').textContent = 'untitled session'; showToast('New session created'); }); $('#saveProject').addEventListener('click', () => showToast('Session saved locally')); $('#renameProject').addEventListener('click', () => { const name = prompt('Name this session', $('#projectTitle').textContent); if (name) $('#projectTitle').textContent = name; });
document.addEventListener('keydown', (event) => { if (event.code === 'Space' && event.target.tagName !== 'INPUT') { event.preventDefault(); state.isPlaying ? stopPlayback() : startPlayback(); } if (event.key === 'Delete') { const selected = $('.note.selected'); if (selected) { state.notes.splice(Number(selected.dataset.index), 1); renderNotes(); } } });